tools = [
    {
        "badgeColor": "#F7DF1E",
        "badgeName": "JavaScript",
        "logoName": "JavaScript",
        "logoColor": "black",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#EC4A3F",
        "badgeName": "Rollup.js",
        "logoName": "Rollup.js",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#3776AB",
        "badgeName": "Python",
        "logoName": "Python",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#339933",
        "badgeName": "Node.js",
        "logoName": "Node.js",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#000000",
        "badgeName": "Bun",
        "logoName": "Bun",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#646CFF",
        "badgeName": "Vite",
        "logoName": "Vite",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#61DAFB",
        "badgeName": "React",
        "logoName": "React",
        "logoColor": "black",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#E34F26",
        "badgeName": "HTML5",
        "logoName": "HTML5",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#E34F26",
        "badgeName": "MySQL",
        "logoName": "MySQL",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#4169E1",
        "badgeName": "PostgreSQL",
        "logoName": "PostgreSQL",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#3178C6",
        "badgeName": "TypeScript",
        "logoName": "TypeScript",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#47A248",
        "badgeName": "MongoDB",
        "logoName": "MongoDB",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#2D3748",
        "badgeName": "Prisma",
        "logoName": "Prisma",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#1572B6",
        "badgeName": "CSS3",
        "logoName": "CSS3",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#E95420",
        "badgeName": "Ubuntu",
        "logoName": "Ubuntu",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#512BD4",
        "badgeName": "C#",
        "logoName": "C#",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#4FC08D",
        "badgeName": "Vue.js",
        "logoName": "Vue.js",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#4EAA25",
        "badgeName": "Bash",
        "logoName": "GNU Bash",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#CC6699",
        "badgeName": "Sass",
        "logoName": "Sass",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#232F3E",
        "badgeName": "AWS",
        "logoName": "Amazon Web Services",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#4285F4",
        "badgeName": "Google Cloud",
        "logoName": "Google Cloud",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#000000",
        "badgeName": "Markdown",
        "logoName": "Markdown",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#1B1F24",
        "badgeName": "MDX",
        "logoName": "MDX",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#F05138",
        "badgeName": "Swift",
        "logoName": "Swift",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#7F52FF",
        "badgeName": "Kotlin",
        "logoName": "Kotlin",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#003545",
        "badgeName": "MariaDB",
        "logoName": "MariaDB",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#47848F",
        "badgeName": "Electron",
        "logoName": "Electron",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#000000",
        "badgeName": "Next.js",
        "logoName": "Next.js",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#3DDC84",
        "badgeName": "Android Studio",
        "logoName": "Android Studio",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#4285F4",
        "badgeName": "Jetpack Compose",
        "logoName": "Jetpack Compose",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#E0234E",
        "badgeName": "Nest.js",
        "logoName": "NestJS",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#000000",
        "badgeName": "iOS",
        "logoName": "iOS",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#000000",
        "badgeName": "macOS",
        "logoName": "macOS",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#000000",
        "badgeName": "JetBrains",
        "logoName": "JetBrains",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#000000",  
        "badgeName": "Fig",
        "logoName": "Fig",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "#FF6C37",
        "badgeName": "Postman",
        "logoName": "Postman",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#73DC8C",
        "badgeName": "HTTPie",
        "logoName": "HTTPie",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#000000",
        "badgeName": "Unity",
        "logoName": "Unity",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#000000",
        "badgeName": "Vercel",
        "logoName": "Vercel",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#F58025",
        "badgeName": "Stack Overflow",
        "logoName": "Stack Overflow",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#FCBFBD",
        "badgeName": "Arc",
        "logoName": "Arc",
        "logoColor": "black",
        "category": "Utilities",
    },
    {
        "badgeColor": "#5865F2",
        "badgeName": "Discord",
        "logoName": "Discord",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#412991",
        "badgeName": "OpenAI",
        "logoName": "OpenAI",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#000000",
        "badgeName": "Notion",
        "logoName": "Notion",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#4687FF",
        "badgeName": "NordVPN",
        "logoName": "NordVPN",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#FF6363",
        "badgeName": "Raycast",
        "logoName": "Raycast",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#721412",
        "badgeName": "OpenSSL",
        "logoName": "OpenSSL",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#7D929E",
        "badgeName": "Aseprite",
        "logoName": "Aseprite",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#E87D0D",
        "badgeName": "Blender",
        "logoName": "Blender",
        "logoColor": "white",
        "category": "Utilities",  
    },
    {
        "badgeColor": "#1F4056",
        "badgeName": "Codecademy",
        "logoName": "Codecademy",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#14BF96",
        "badgeName": "Khan Academy",
        "logoName": "Khan Academy",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#000000",
        "badgeName": "CodePen",
        "logoName": "CodePen",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#0F2B46",
        "badgeName": "DeepL",
        "logoName": "DeepL",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#025E8C",
        "badgeName": "Dependabot",
        "logoName": "Dependabot",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#F08705",
        "badgeName": "diagrams.net",
        "logoName": "diagrams.net",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#EB844E",
        "badgeName": "Fireship",
        "logoName": "Fireship",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#000000",
        "badgeName": "GitHub Copilot",
        "logoName": "GitHub Copilot",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#FF6666",
        "badgeName": "Giphy",
        "logoName": "Giphy",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#FF90E8",
        "badgeName": "Gumroad",
        "logoName": "Gumroad",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#673DE6",
        "badgeName": "Hostinger",
        "logoName": "Hostinger",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#1BB76E",
        "badgeName": "Imgur",
        "logoName": "Imgur",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#E4405F",
        "badgeName": "Instagram",
        "logoName": "Instagram",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#000000",
        "badgeName": "Medium",
        "logoName": "Medium",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#0A66C2",
        "badgeName": "LinkedIn",
        "logoName": "LinkedIn",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#FF4500",
        "badgeName": "Reddit",
        "logoName": "Reddit",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#000000",
        "badgeName": "X (Twitter)",
        "logoName": "X",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#00B8FC",
        "badgeName": "Logitech",
        "logoName": "Logitech",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#4945FF",
        "badgeName": "Strapi",
        "logoName": "Strapi",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#3FCF8E",
        "badgeName": "Supabase",
        "logoName": "Supabase",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#85EA2D",
        "badgeName": "Swagger",
        "logoName": "Swagger",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#06B6D4",
        "badgeName": "Tailwind CSS",
        "logoName": "Tailwind CSS",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#666666",
        "badgeName": "Internet Archive",
        "logoName": "Internet Archive",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#3693F3",
        "badgeName": "iCloud",
        "logoName": "iCloud",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#5E5E5E",
        "badgeName": "Microsoft",
        "logoName": "Microsoft",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#3C8527",
        "badgeName": "Minecraft",
        "logoName": "Minecraft",
        "logoColor": "white",
        "category": "Utilities",        
    },
    {
        "badgeColor": "#EF323D",
        "badgeName": "Mojang",
        "logoName": "Mojang Studios",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#40BE46",
        "badgeName": "JFrog",
        "logoName": "JFrog",
        "logoColor": "white",
        "category": "Utilities",   
    },
    {
        "badgeColor": "#000000",
        "badgeName": "JWT",
        "logoName": "JSON Web Tokens",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "#179287",
        "badgeName": "GitKraken",
        "logoName": "GitKraken",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "#181717",
        "badgeName": "GitHub",
        "logoName": "GitHub",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "#FC6D26",
        "badgeName": "GitLab",
        "logoName": "GitLab",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "#F05032",
        "badgeName": "Git",
        "logoName": "Git",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "#2496ED",
        "badgeName": "Docker",
        "logoName": "Docker",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "#007ACC",
        "badgeName": "VS Code",
        "logoName": "Visual Studio Code",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "#CB3837",
        "badgeName": "NPM",
        "logoName": "npm",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "#326CE5",
        "badgeName": "Kubernetes",
        "logoName": "Kubernetes",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "#8DD6F9",
        "badgeName": "Webpack",
        "logoName": "Webpack",
        "logoColor": "black",
        "category": "DevOps",
    },
    {
        "badgeColor": "#000000",
        "badgeName": "IntelliJ IDEA",
        "logoName": "IntelliJ IDEA",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "#2088FF",
        "badgeName": "GitHub Actions",
        "logoName": "GitHub Actions",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "#4B32C3",
        "badgeName": "ESLint",
        "logoName": "ESLint",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "#02303A",
        "badgeName": "Gradle",
        "logoName": "Gradle",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "#EE0000",
        "badgeName": "Ansible",
        "logoName": "Ansible",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "#147EFB",
        "badgeName": "Xcode",
        "logoName": "Xcode",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "#C21325",
        "badgeName": "Jest",
        "logoName": "Jest",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "#F7B93E",
        "badgeName": "Prettier",
        "logoName": "Prettier",
        "logoColor": "black",
        "category": "DevOps",
    },
    {
        "badgeColor": "#FBB040",
        "badgeName": "Homebrew",
        "logoName": "Homebrew",
        "logoColor": "black",
        "category": "DevOps",
    },
    {
        "badgeColor": "#4A154B",
        "badgeName": "Slack",
        "logoName": "Slack",
        "logoColor": "white",
        "category": "Business Tools",
    },
    {
        "badgeColor": "#F24E1E",
        "badgeName": "Figma",
        "logoName": "Figma",
        "logoColor": "white",
        "category": "Business Tools",
    },
]

for tool in tools:
    tool["badgeColor"] = tool["badgeColor"].replace("#", "")
    badge_url = f"https://img.shields.io/badge/-{tool['badgeName']}-{tool['badgeColor']}?style=flat-square&logo={tool['logoName']}&logoColor={tool['logoColor']}"
    print(f'<img alt="{tool["badgeName"]}" src="{badge_url}" />')
