tools = [
    {
        "badgeColor": "F7DF1E",
        "badgeName": "JavaScript",
        "logoName": "JavaScript",
        "logoColor": "black",
        "category": "Application and Data",
    },
    {
        "badgeColor": "3776AB",
        "badgeName": "Python",
        "logoName": "Python",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "339933",
        "badgeName": "Node.js",
        "logoName": "Node.js",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "61DAFB",
        "badgeName": "React",
        "logoName": "React",
        "logoColor": "black",
        "category": "Application and Data",
    },
    {
        "badgeColor": "E34F26",
        "badgeName": "HTML5",
        "logoName": "HTML5",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "007396",
        "badgeName": "Java",
        "logoName": "Java",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "4479A1",
        "badgeName": "MySQL",
        "logoName": "MySQL",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "4169E1",
        "badgeName": "PostgreSQL",
        "logoName": "PostgreSQL",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "3178C6",
        "badgeName": "TypeScript",
        "logoName": "TypeScript",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "47A248",
        "badgeName": "MongoDB",
        "logoName": "MongoDB",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "1572B6",
        "badgeName": "CSS3",
        "logoName": "CSS3",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "E95420",
        "badgeName": "Ubuntu",
        "logoName": "Ubuntu",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "239120",
        "badgeName": "C#",
        "logoName": "C#",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "4FC08D",
        "badgeName": "Vue.js",
        "logoName": "Vue.js",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "4EAA25",
        "badgeName": "Shell",
        "logoName": "Shell",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "CC6699",
        "badgeName": "Sass",
        "logoName": "Sass",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "61DAFB",
        "badgeName": "React Native",
        "logoName": "React Native",
        "logoColor": "black",
        "category": "Application and Data",
    },
    {
        "badgeColor": "232F3E",
        "badgeName": "AWS",
        "logoName": "AWS",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "4285F4",
        "badgeName": "Google Cloud",
        "logoName": "Google Cloud",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "000000",
        "badgeName": "Markdown",
        "logoName": "Markdown",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "FA7343",
        "badgeName": "Swift",
        "logoName": "Swift",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "0095D5",
        "badgeName": "Kotlin",
        "logoName": "Kotlin",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "003545",
        "badgeName": "MariaDB",
        "logoName": "MariaDB",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "47848F",
        "badgeName": "Electron",
        "logoName": "Electron",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "000000",
        "badgeName": "Next.js",
        "logoName": "Next.js",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "E0234E",
        "badgeName": "Nest.js",
        "logoName": "Nest.js",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "000000",
        "badgeName": "macOS",
        "logoName": "macOS",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "FF6363",  
        "badgeName": "Fig",
        "logoName": "Fig",
        "logoColor": "white",
        "category": "Application and Data",
    },
    {
        "badgeColor": "FF6C37",
        "badgeName": "Postman",
        "logoName": "Postman",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "F58025",
        "badgeName": "Stack Overflow",
        "logoName": "Stack Overflow",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "00457C",
        "badgeName": "PayPal",
        "logoName": "PayPal",
        "logoColor": "white",
        "category": "Utilities",
    },
    {
        "badgeColor": "F05032",
        "badgeName": "Git",
        "logoName": "Git",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "181717",
        "badgeName": "GitHub",
        "logoName": "GitHub",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "2496ED",
        "badgeName": "Docker",
        "logoName": "Docker",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "007ACC",
        "badgeName": "VS Code",
        "logoName": "VS Code",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "CB3837",
        "badgeName": "npm",
        "logoName": "npm",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "326CE5",
        "badgeName": "Kubernetes",
        "logoName": "Kubernetes",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "8DD6F9",
        "badgeName": "Webpack",
        "logoName": "Webpack",
        "logoColor": "black",
        "category": "DevOps",
    },
    {
        "badgeColor": "000000",
        "badgeName": "IntelliJ IDEA",
        "logoName": "IntelliJ IDEA",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "2088FF",
        "badgeName": "GitHub Actions",
        "logoName": "GitHub Actions",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "4B32C3",
        "badgeName": "ESLint",
        "logoName": "ESLint",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "02303A",
        "badgeName": "Gradle",
        "logoName": "Gradle",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "EE0000",
        "badgeName": "Ansible",
        "logoName": "Ansible",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "147EFB",
        "badgeName": "Xcode",
        "logoName": "Xcode",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "66595C",
        "badgeName": "Atom",
        "logoName": "Atom",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "C21325",
        "badgeName": "Jest",
        "logoName": "Jest",
        "logoColor": "white",
        "category": "DevOps",
    },
    {
        "badgeColor": "F7B93E",
        "badgeName": "Prettier",
        "logoName": "Prettier",
        "logoColor": "black",
        "category": "DevOps",
    },
    {
        "badgeColor": "FBB040",
        "badgeName": "Homebrew",
        "logoName": "Homebrew",
        "logoColor": "black",
        "category": "DevOps",
    },
    {
        "badgeColor": "4A154B",
        "badgeName": "Slack",
        "logoName": "Slack",
        "logoColor": "white",
        "category": "Business Tools",
    },
    {
        "badgeColor": "FF6363",
        "badgeName": "Figma",
        "logoName": "Figma",
        "logoColor": "white",
        "category": "Business Tools",
    },
]

for tool in tools:
    badge_url = f"https://img.shields.io/badge/-{tool['badgeName']}-{tool['badgeColor']}?style=flat-square&logo={tool['logoName']}&logoColor={tool['logoColor']}"
    print(f'<img alt="{tool["badgeName"]}" src="{badge_url}" />')
